controller:
  ingressClass: nginx-trial
  ingressClassResource:
    name: nginx-trial
    enabled: true
    default: false
    controllerValue: "k8s.io/nginx-trial"

  service:
    type: NodePort
    nodePorts:
      http: 31081
      https: 32444

  metrics:
    enabled: true

defaultBackend:
  enabled: false
