controller:
  ingressClass: nginx-dev
  ingressClassResource:
    name: nginx-dev
    enabled: true
    default: false
    controllerValue: "k8s.io/nginx-dev"

  service:
    type: NodePort
    nodePorts:
      http: 31080
      https: 31443

  metrics:
    enabled: true

defaultBackend:
  enabled: false
