all:
  children:
    k3s:
      hosts:
        k3s-node-1:
          ansible_host: 10.0.0.40
          ansible_user: a3888s
          ansible_ssh_private_key_file: /home/a3888s/.ssh/id_rsa
          ansible_port: 22276