apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-root-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/a3888s/project-root.git'
    targetRevision: main
    path: app/k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true