apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-root-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/a3888s/project-root.git'
    targetRevision: dev
    path: app/k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
